### ISSUE TITLE
trying to replicate

### ISSUE THREAD

**Issue by stonebig** [ogrisel/python-appveyor-demo#2]
Hi Olivier,

Thank you for the demo project, I'm up and running after a few minutes.

But there is already a strange issue : what builds on your account doesn't build on mine.

https://ci.appveyor.com/project/stonebig/python-appveyor-demo/build/1.0.1

Have you an idea of the problem ?

**Comment by stonebig** [comment]
are you sure the followin instruction from pycon2015 works ?

````
"pip install dist/*"
````

I get a bad Appveyor response:
https://ci.appveyor.com/project/stonebig/sqlite-bro/build/job/aii9crmbwqr6q80p

````
creating build\bdist.win32\wheel\sqlite_bro-0.8.7.4.dist-info\WHEEL
ls dist
 
 
    Directory: C:\projects\sqlite-bro\dist
 
 
Mode                LastWriteTime     Length Name                                                                                                                                                                                    
----                -------------     ------ ----                                                                                                                                                                                    
-a---         4/13/2015   4:33 PM      26862 sqlite_bro-0.8.7.4-py2.py3-none-any.whl                                                                                                                                                 
 
 
pip install dist/*
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "C:\Python27\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "C:\Python27\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'dist/*', 'at', '/*')
 
Storing debug log for failure in C:\Users\appveyor\pip\pip.log
Command exited with code 2
````

**Comment by stonebig** [comment]
trying with this 
````
  - "dir/b dist"
  - "dir/b dist>toto.txt"
  - "for /f "delims=" %f in (toto.txt) DO Set MyVar=%f && pip install dist/%MyVar%"
````

**Comment by ogrisel** [comment]
Indeed, I edited my slide to simply stuff but I am likely to have broken stuff in the process (at list under windows). I think it's a bug of `pip install` that should use `glob.glob`.


A temporary workaround:

```
pip install --pre --no-index --find-links dist/ package_name
```

**Comment by stonebig** [comment]
ah, will try it. I'm at my 18th workaround at the moment

**Comment by ogrisel** [comment]
Let me know if it fixes it for you.

**Comment by stonebig** [comment]
Yes, it did, and it's functionnally a better and simpler solution.

https://ci.appveyor.com/project/stonebig/sqlite-bro/build/1.0.22

Merci et bon voyage de retour en France.
